#!/usr/bin/env python3

from datetime import datetime
import json
from time import mktime

import feedparser
import pytz

def timestruct_to_rfc3339(timestruct):
    return (pytz.utc.localize(datetime.fromtimestamp(mktime(timestruct)))
            .isoformat())

rss_feed = feedparser.parse('https://www.denverpost.com/news/colorado/feed/')
json_feed = {
    'version': 'https://jsonfeed.org/version/1.1',
    'title': 'Denverite: Denver News',
    'home_page_url': 'https://sreynen.github.io/denver-news/',
    'feed_url': 'https://sreynen.github.io/denver-news/denverite.json',
    'items': []
}

for entry in rss_feed.entries:
    json_feed['items'].append({
        'id': entry.link,
        'url': entry.link,
        'title': entry.title,
        'date_published': timestruct_to_rfc3339(entry.published_parsed),
        'date_modified': timestruct_to_rfc3339(entry.updated_parsed)
    })

with open('./json/denver-post.json', 'w', encoding='utf8') as json_file:
    json.dump(json_feed, json_file)
