name: Update news

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '17 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Python requirements
      run: |-
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Scrape Denver Post
      run: |-
        ./scrape/denver_post
    - name: Scrape 9News
      run: |-
        ./scrape/9news
    - name: Scrape Denverite
      run: |-
        ./scrape/denverite
    - name: Generate HTML
      run: |-
        ./generate_html
    - name: Copy JSON files
      run: |-
        cp ./json/denver-post.json ./docs/denver-post.json
        cp ./json/9news.json ./docs/9news.json
        cp ./json/denverite.json ./docs/denverite.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest update: ${timestamp}" || exit 0
        git push
